command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: ENV
    value: "production"
  - name: PORT
    value: "8000"
  - name: DEBUG
    value: "False"

resources:
  cpu: "1"
  memory: "2Gi"

description: "Capacity Management application - A modern React + FastAPI app with MUI and Framer Motion"
